'use strict';var CommentPreview={commentForm:null,defaultName:"",gravSize:48,gravUrl:"",previewAvatar:null,previewContent:null,previewName:null,addListeners:function(){var a;a=this.commentForm.querySelector("[name=comment-author-name]");a.addEventListener("keyup",this.update.bind(this));a=this.commentForm.querySelector("[name=comment-author-email]");a.addEventListener("change",this.update.bind(this));a=this.commentForm.querySelector("[name=comment-author-url]");a.addEventListener("change",this.update.bind(this));
a=this.commentForm.querySelector("[name=comment-content]");a.addEventListener("keyup",this.update.bind(this))},createPreview:function(){this.previewAvatar=document.createElement("img");this.previewAvatar.setAttribute("alt","avatar");this.previewAvatar.className="avatar";this.previewAvatar.src=this.gravUrl+"?d=mm&s="+this.gravSize;this.previewName=document.createElement("span");this.previewName.className="comment-author";this.previewName.textContent=this.defaultName;var a=document.createElement("span");
a.className="comment-time";a.textContent="preview";var b=document.createElement("div");b.className="comment-meta";b.appendChild(this.previewAvatar);b.appendChild(this.previewName);b.appendChild(a);this.previewContent=document.createElement("div");this.previewContent.className="comment-content";a=document.createElement("div");a.className="comment preview";a.appendChild(b);a.appendChild(this.previewContent);b=document.createDocumentFragment();b.appendChild(a);b.appendChild(document.createElement("hr"));
document.getElementById("comments").appendChild(b)},init:function(a,b,c){this.gravUrl=a;this.gravSize=b;this.defaultName=c;this.commentForm=document.getElementById("comment-form");null!=this.commentForm&&this.addListeners()},update:function(a){null==this.previewContent&&this.createPreview();switch(a.target.name){case "comment-author-name":this.updateName(a);break;case "comment-author-email":this.updateMail(a);break;case "comment-author-url":this.updateUrl(a);break;case "comment-content":this.updateContent(a)}},
updateContent:function(a){a=a.target.value;a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");a=a.replace(/&lt;(blockquote|code|del|em|strong)&gt;/gi,"<$1>");a=a.replace(/&lt;\/(a|blockquote|code|del|em|strong)&gt;/gi,"</$1>");a=a.replace(/&lt;a href="([^\'"]+)"&gt;/gi,'<a href="$1">');a=a.replace(/&lt;(br) \/&gt;/gi,"<$1 />");a=a.replace(/\r\n|\n\r|\r|\n/g,"<br />");this.previewContent.innerHTML=a},updateMail:function(a){this.previewAvatar.src=this.gravUrl+md5(a.target.value)+
"?d=mm&s="+this.gravSize},updateName:function(a){a=a.target.value.trim();0==a.length&&(a=this.defaultName);this.previewName.textContent=a},updateUrl:function(a){a=a.target.value.toLowerCase();var b;0==this.previewName.textContent.length&&(this.previewName.textContent=this.defaultName);if(0>=a.length||null==a.match(/^((http|ftp)s?:\/\/)?[^\s"']+$/)){if("span"==this.previewName.tagName)return;b=document.createElement("span")}else null==a.match(/^(http|ftp)s?:\/\//)&&(a="http://"+a),b=document.createElement("a"),
b.href=a;b.className="comment-author";b.textContent=this.previewName.textContent;this.previewName.parentNode.replaceChild(b,this.previewName);this.previewName=b}},CommentValidate={commentForm:null,commentContent:null,commentEmail:null,highlightError:function(a){a.className+=" invalid"},init:function(){this.commentForm=document.getElementById("comment-form");this.commentContent=this.commentForm.querySelector("[name=comment-content]");this.commentEmail=this.commentForm.querySelector("[name=comment-author-email]");
this.commentForm.addEventListener("submit",this.validate.bind(this))},resetStatus:function(){this.commentContent.className=this.commentContent.className.replace(" invalid","");this.commentEmail.className=this.commentEmail.className.replace(" invalid","")},validate:function(a){this.resetStatus();0>=this.commentContent.value.length&&(a.preventDefault(),this.highlightError(this.commentContent));0<this.commentEmail.value.length&&null==this.commentEmail.value.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)&&(a.preventDefault(),
this.highlightError(this.commentEmail))}};
